// Names of the Octicons the app shows from plain data (feed events, session options, alerts).
// components/Icon.tsx maps each to its Octicon.
export type IconName =
  | 'alert'
  | 'chat'
  | 'check-circle'
  | 'check-circle-fill'
  | 'checklist'
  | 'code-review'
  | 'comment'
  | 'comment-discussion'
  | 'dependabot'
  | 'eye'
  | 'file'
  | 'file-diff'
  | 'git-commit'
  | 'git-merge'
  | 'git-pull-request'
  | 'git-pull-request-closed'
  | 'issue-reopened'
  | 'paper-airplane'
  | 'repo-push'
  | 'stop'
  | 'sync'
  | 'x-circle'
